CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,
    email VARCHAR(200) UNIQUE NOT NULL CHECK (email LIKE('%@%')),
    password_hash VARCHAR(200) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE companies (
    id BIGSERIAL PRIMARY KEY,
    company_name VARCHAR(100) NOT NULL,
    website TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE job_applications (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT REFERENCES users (id) NOT NULL ,
    company_id BIGINT REFERENCES companies (id) NOT NULL,
    position VARCHAR(100) NOT NULL,
    status VARCHAR(30) NOT NULL CHECK ( status IN ('APPLIED', 'SAVED', 'INTERVIEW', 'REJECTED')),
    salary_expectation INTEGER,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);